### ISSUE TITLE
Cannot launch Flatpak apps

### ISSUE THREAD

**Issue by IlyaBizyaev** [lirios/flatpak-apps#1]
The following problem occurs:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```
Tested on Browser and Calculator. Flatpak 0.9.1 on openSUSE Leap 42.2.

**Comment by Aldrog** [comment]
If you have NVIDIA driver, try `sudo flatpak install gnome org.freedesktop.Platform//1.6`.
It should get you a correct OpenGL driver.

**Comment by IlyaBizyaev** [comment]
Thanks, works now!
